### ISSUE TITLE
Deploy Redirector (deploy.cloud.run)

### ISSUE THREAD

**Issue by jamesward** [GoogleCloudPlatform/cloud-run-button#16]
I think we should create a service (on Cloud Run) which gives us a short and custom URL we can link to for the button so that we can:

- be isolated from underlying URL which we redirect to
- possibly support the referrer so the git URL is optional
- track deploy metrics (#13)
- set current or future defaults

So the button href cloud be just something like:
`https://cloud.run/deploy`

Maybe @steren can chime in on possibly using the existing `cloud.run` domain.

**Comment by steren** [comment]
That's a great idea, and what I originally had in mind for `cloud.run` 

Google owns `cloud.run`, so that's definitely possible, however, there are processes and delays associated with changing its DNS. And I am also not sure how it can be associated with a Cloud Run service. We'll investigate.

Let's start by creating the service that does the redirect, once we have something up, I can take care of the domain.

**Comment by ahmetb** [comment]
SGTM. We can make part of this repo and its build process, and deploy to the same Cloud Run - PROD project.

If anyone wants to code up something simple in Go at `./cmd/redirect`, I'll leave it up for grabs.

**Comment by steren** [comment]
a suggestion was to use `deploy.cloud.run`, as it might be easier to configure.

**Comment by ahmetb** [comment]
Can someone sketch out an example for this? I'm having trouble imagining how would this look like. Our current URLs aren't that bad and they're likely to outlive the button (since they're part of Open in Cloud Shell API documented here https://cloud.google.com/shell/docs/open-in-cloud-shell).

Unless we do something like Referer check + auto-detect the git repo, I'm not entirely sure if `console.cloud.google.com/cloudshell/editor?shellonly=true&...` &rarr; `deploy.cloud.run?...` is a worthy improvement.

**Comment by steren** [comment]
I think using a custom domain would:

1. minor: be nicer in markdown (cosmetic)
2. major: shield the buttom from its implementation. Indeed, we could imagine that in the future, this is flow would be directly supported by the a page in the Cloud Console.

**Comment by ahmetb** [comment]
I've confirmed that when a button is clicked from GitHub, it preserves the `Referer` header which can help us find the git repo (and perhaps the subdirectory) so that people can even add the Markdown to their repo without even changing any parameters.
