### ISSUE TITLE
Handling When No Projects Exist

### ISSUE THREAD

**Issue by jamesward** [GoogleCloudPlatform/cloud-run-button#22]
When no projects exist, create one for them, like:
```
PROJECT_NAME="$1-$((1 + RANDOM % 10000))"
    gcloud projects create $PROJECT_NAME --set-as-default --quiet 2> /dev/null
    if [[ "$?" -eq 0 ]]; then
      break
    fi
    sleep 1
```

**Comment by jamesward** [comment]
BTW, This exists in the existing button and I don't think we should drop it.

**Comment by ahmetb** [comment]
I think we should drop it in its current form, as the experience to create a project is much better in the UI.

There are way too many corner cases of project creation like associating a billing account, folders, organizations, setting a description etc. Corporate accounts have enforcements we may not be able to satisfy in the CLI. So let's not reinvent what's already in the UI (+nicer).

I'm proposing in #25 we fail when no project exists (so users can refresh to continue).

I think to close this issue fully, I say we move ahead with #25, and later on we refactor it in a way that instead of failing, we wait and say "Click here to create a project ...", + prompt and say "Click enter when you’re done".

**Comment by jamesward** [comment]
I agree with that assessment and plan.
