### ISSUE TITLE
Provide a command I can run to re-deploy after making changes

### ISSUE THREAD

**Issue by ImJasonH** [GoogleCloudPlatform/cloud-run-button#70]
After clicking the button and following prompts, I now have a deployed app, and the source for that app cloned in my Cloud Shell.

I'd love to be able to modify the source and redeploy to the app again, but I don't know how. Looking in history, it looks like I originally deployed using `cloudshell_open` but it takes a `-repo_url` which will presumably re-clone the repo, instead of just deploying my changes.

**Comment by ahmetb** [comment]
This is pretty challenging, because we hijack cloudshell_open command that cloud shell normally uses (to clone repos for Open in Cloud Shell functionality).

To mitigate this, we provide many output messages, such as:

```
[ ! ] FYI, running the following command:
        docker build -t gcr.io/x/cloud-run-hello .
[ ✓ ] Built container image gcr.io/x/cloud-run-hello
[ ! ] FYI, running the following command:
        docker push gcr.io/x/cloud-run-hello
[ ✓ ] Pushed container image to Google Container Registry.
[ ! ] FYI, running the following command:
        gcloud beta run deploy cloud-run-hello\
          --project=x\
          --platform=managed\
          --region=us-east1\
          --image=gcr.io/x/cloud-run-hello\
          --memory=512Mi\
          --allow-unauthenticated
```

have you noticed these while the app was being deployed? The purpose of these FYI messages are to educate the users about how they can replicate the same workflow locally (or in Cloud Shell).

**Comment by ImJasonH** [comment]
I see. So Cloud Shell expects to find/run a binary named `cloudshell_open` which under normal circumstances requires a `--repo_url` flag, which tells Cloud Shell what repo to clone, is that correct?

Would it be possible for your container image to either include other binaries on the `PATH` (something like `refresh_cloud_run`), or accept other flag specs to `cloudshell_open` which would skip the clone step?

I didn't really pay attention to the logs as they streamed by. If the last line had said `Run refresh_cloud_run after making changes to re-deploy` or `Run cloudshell_open --cloud-run-button ...` that could have helped. That would also let you bundle multiple commands together and have more control over the refresh experience.

Let me know if this is something you'd be interested in, and maybe I can try making a PR for it.

**Comment by ahmetb** [comment]
Good points, I guess users want to see some repro steps at the end, however we tried to keep the last part of the output short with:
- deployed URL
- pricing model
- what's next (link to docs)

I still think showing these commands as they're executed is better. Since these commands take a while, user has the time to read it (and we have some visual UI cues like `[!]`).

If the user wants to see them, they can probably just scroll  up?

**Comment by ImJasonH** [comment]
Fair enough. Thanks for your response, and for this project!
