### ISSUE TITLE
Service Name Contraints

### ISSUE THREAD

**Issue by jamesward** [GoogleCloudPlatform/cloud-run-button#9]
See: https://github.com/jamesward/cloud-run-button/issues/4

**Comment by ahmetb** [comment]
I am inclined to keep it with fewer prompts, but we can easily add an extra prompt with a default value.

**Comment by ahmetb** [comment]
I am reading they ran into it mostly because they wanted to support gists. Do we actually try to make this use case possible? If not, we can probably roll without the sanitization/replacements much longer. (I suspect people don’t create repo names with underscores or leading digits much).

Still easily doable.

**Comment by jamesward** [comment]
Yeah, it was to support gist git repos.  It works now.  But to customize the service name they can just put an `app.json` in the gist too.

This issue is just to make sure we are doing the at least the same santitization stuff as I did to support gists out-of-the-box.
